# Generated by Django 3.0.5 on 2020-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
