# Generated by Django 3.0.5 on 2020-09-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0002_trainer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipet',
            name='trainers',
        ),
        migrations.AddField(
            model_name='ekipet',
            name='trainers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ekipet.Trainer'),
        ),
    ]
