# Generated by Django 3.0.5 on 2020-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0003_auto_20200914_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipet',
            name='trainers',
        ),
        migrations.AddField(
            model_name='ekipet',
            name='trainers',
            field=models.ManyToManyField(default=None, to='Ekipet.Trainer'),
        ),
    ]
