# Generated by Django 3.0.5 on 2020-09-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0004_auto_20200915_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipet',
            name='trainers',
        ),
        migrations.AddField(
            model_name='trainer',
            name='team',
            field=models.ManyToManyField(related_name='ekip', to='Ekipet.Ekipet'),
        ),
    ]
