# Generated by Django 3.0.5 on 2020-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0005_auto_20200915_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='team',
        ),
        migrations.AddField(
            model_name='ekipet',
            name='trainers',
            field=models.ManyToManyField(default=None, to='Ekipet.Trainer'),
        ),
    ]
