# Generated by Django 3.0.5 on 2020-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekipet', '0006_auto_20200915_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipet',
            name='trainers',
            field=models.ManyToManyField(default=None, related_name='profesor', to='Ekipet.Trainer'),
        ),
    ]
