# Generated by Django 3.0.5 on 2020-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='team',
        ),
        migrations.AddField(
            model_name='ekipet',
            name='trainers',
            field=models.ManyToManyField(related_name='team', to='blog.Trainers'),
        ),
    ]
