# Generated by Django 3.0.5 on 2020-09-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200912_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ekipet',
            name='trainers',
        ),
        migrations.DeleteModel(
            name='KontaktEmail',
        ),
        migrations.DeleteModel(
            name='KontaktNumber',
        ),
        migrations.DeleteModel(
            name='Ekipet',
        ),
        migrations.DeleteModel(
            name='Grupmoshat',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
