# Generated by Django 3.0.5 on 2020-09-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ManySlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='many_slides', to='blog.Slide')),
            ],
        ),
    ]
