# Generated by Django 3.0.5 on 2020-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_manyslide_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manyslide',
            old_name='slide',
            new_name='relation',
        ),
        migrations.AddField(
            model_name='manyslide',
            name='slider',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
