# Generated by Django 3.0.5 on 2020-09-15 12:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=blog.models.get_image_filename, verbose_name='Images'),
        ),
    ]
