# Generated by Django 3.0.5 on 2020-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200915_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FronSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slide', models.ImageField(upload_to='slide_pics')),
                ('rendesia', models.IntegerField()),
            ],
        ),
    ]
