# Generated by Django 3.0.5 on 2020-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_fronslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronslider',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
