# Generated by Django 3.0.5 on 2020-09-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_fronslider_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FronSlider',
            new_name='FrontSlider',
        ),
    ]
